import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' }, // Keep this for auto-generated docs

    {
      type: 'html',
      value: '<div class="subscribe-container"><iframe src="https://blog.dataleadership.ai/embed" width="280" height="320" style="border: 1px solid #EEE; background: white;" frameBorder="0" scrolling="no"></iframe></div>',
      className: 'subscribe-sidebar',
    },
    {
      type: 'html',
      value: '<div class="linkedin-profile"><img src="/img/ryanvarley-profile.jpeg" alt="Ryan Varley Profile Picture" width="100" height="100" style="border-radius: 50%; object-fit: cover;" /><p>Follow me on LinkedIn</p></div>',
      className: 'linkedin-profile-sidebar',
    },
  ],
};

export default sidebars;