import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'html',
      value: '<div style="margin-top: 20px;"><iframe src="https://blog.dataleadership.ai/embed" width="280" height="320" style="border: 1px solid #EEE; background: white;" frameBorder="0" scrolling="no""></iframe></div>',
      // You can add a custom className for styling:
      className: 'subscribe-sidebar',
    },
    {
      type: 'html',
      value: '<div style="margin-top: 20px; text-align: center;"><img src="/img/ryanvarley-profile.jpeg" alt="Ryan Varley Profile Picture" style="width: 100px; height: 100px; border-radius: 50%; object-fit: cover;"><p style="margin-top: 10px;">Follow me on LinkedIn</p></div>',
      className: 'linkedin-profile-sidebar',
    },
  ]


};